import { socialConfig } from "./app-config";

export const mockConfig = {
  filmData: [
    {
      Slug: "001",
      Title: "001",
      Camera: "Sony A7C2",
      Lens: "Nikon AF-S NIKKOR 24-70mm",
      Speed: "1/400s",
      Aperature: "f/4.50",
      ISO: 400,
      Location: "Seoul, Korea",
      Date: "2025-09-05T00:00:00.000Z",
      Image:
        "https://framerusercontent.com/images/XGZJ6qirFT7cLdKV7u1U7OVNqE.jpeg?scale-down-to=1024&width=1024&height=1536",
      "Image:alt": "",
      Video: null,
    },
    {
      Slug: "002",
      Title: "002",
      Camera: "Sony A7C2",
      Lens: "Nikon AF-S NIKKOR 24-70mm",
      Speed: "1/400s",
      Aperature: "f/4.50",
      ISO: 400,
      Location: "Seoul, Korea",
      Date: "2025-09-24T00:00:00.000Z",
      Image:
        "https://framerusercontent.com/images/t75nyvQ1dEu2xfy7dPewY1UPrc.jpeg?width=683&height=1024",
      "Image:alt": "",
      Video: null,
    },
    {
      Slug: "003",
      Title: "003",
      Camera: "Sony A7C2",
      Lens: "Nikon AF-S NIKKOR 24-70mm",
      Speed: "1/400s",
      Aperature: "f/4.50",
      ISO: 400,
      Location: "Seoul, Korea",
      Date: "2025-06-15T00:00:00.000Z",
      Image:
        "https://framerusercontent.com/images/J4En2AwYVApCjdsUeMpB2xlaiw.jpg?width=2264&height=4027",
      "Image:alt": "Gothic window with diamond-shaped glass panes",
      Video: null,
    },
    {
      Slug: "004",
      Title: "004",
      Camera: "Sony A7C2",
      Lens: "Nikon AF-S NIKKOR 24-70mm",
      Speed: "1/400s",
      Aperature: "f/4.50",
      ISO: 400,
      Location: "Seoul, Korea",
      Date: "2025-09-02T00:00:00.000Z",
      Image:
        "https://framerusercontent.com/images/XnRGSpHhV2iCYg66SRDl7tzIXw.jpeg?width=896&height=1280",
      "Image:alt": "",
      Video: null,
    },
    {
      Slug: "005",
      Title: "005",
      Camera: "Sony A7C2",
      Lens: "Nikon AF-S NIKKOR 24-70mm",
      Speed: "1/400s",
      Aperature: "f/4.50",
      ISO: 400,
      Location: "Seoul, Korea",
      Date: "2025-09-28T00:00:00.000Z",
      Image:
        "https://framerusercontent.com/images/NRVZQ2QozH5sI4eKARuVb4gqFg.jpeg?width=1472&height=1736",
      "Image:alt": "",
      Video: null,
    },
    {
      Slug: "006",
      Title: "006",
      Camera: "Sony A7C2",
      Lens: "Nikon AF-S NIKKOR 24-70mm",
      Speed: "1/400s",
      Aperature: "f/4.50",
      ISO: 400,
      Location: "Seoul, Korea",
      Date: "2025-07-08T00:00:00.000Z",
      Image: null,
      "Image:alt": "",
      Video:
        "https://framerusercontent.com/assets/N8d7dQq3K5j4KWTKmkj40yKc8Cg.mp4",
    },
    {
      Slug: "007",
      Title: "007",
      Camera: "Sony A7C2",
      Lens: "Nikon AF-S NIKKOR 24-70mm",
      Speed: "1/400s",
      Aperature: "f/4.50",
      ISO: 400,
      Location: "Seoul, Korea",
      Date: "2025-09-09T00:00:00.000Z",
      Image:
        "https://framerusercontent.com/images/JzLtxNubVtEVKBNA0Lw5jxdc6Qw.jpeg?width=896&height=1280",
      "Image:alt": "",
      Video: null,
    },
    {
      Slug: "008",
      Title: "008",
      Camera: "Sony A7C2",
      Lens: "Nikon AF-S NIKKOR 24-70mm",
      Speed: "1/400s",
      Aperature: "f/4.50",
      ISO: 400,
      Location: "Seoul, Korea",
      Date: "2025-09-27T00:00:00.000Z",
      Image:
        "https://framerusercontent.com/images/Eex7RbmOegvUGj8haRtC8xYhWY.jpeg?width=768&height=1408",
      "Image:alt": "",
      Video: null,
    },
  ],
  archivesData: [
    {
      Slug: "nopal",
      Title: "Nopal",
      "Homepage Featured": true,
      "Project Number": 6,
      "Next Project 1": 5,
      "Next Project 2": 4,
      "Next Project 3": 3,
      Tagline: "Designing the future of sustainable agriculture",
      Client: "",
      Year: 2025,
      Location: "CDMX, Mexico",
      Info: "Nopal Tech, a sustainable agriculture SaaS startup, needed a future-forward brand identity. I designed a clean, modern logo, visual system for presentations and pitch decks, and website assets that helped position them as leaders in their field.",
      "External Link": "https://framer.link/ludoviclosco",
      Services: "digital,marketing-materials",
      Credits: "<p>Images generated with AI</p>",
      "Thumbnail Image (Portrait 4:5)":
        "https://framerusercontent.com/images/vtTWbuKH7FC9Ewclc30meQkFA.jpg?width=3840&height=2160",
      "Thumbnail Image (Portrait 4:5):alt": "",
      "Thumbnail Video (Portrait 4:5)": "",
      "Thumbnail Video Poster (Portrait 4:5)": "",
      "Thumbnail Video Poster (Portrait 4:5):alt": "",
      "Featured Image (Landscape 16:9)":
        "https://framerusercontent.com/images/vtTWbuKH7FC9Ewclc30meQkFA.jpg?width=3840&height=2160",
      "Featured Image (Landscape 16:9):alt": "",
      "Image 1 (Portrait 4:5)":
        "https://framerusercontent.com/images/WLJQduFa6kJyPUYts7PLBSvy2A.jpg",
      "Image 1 (Portrait 4:5):alt": "",
      "Image 2 (Portrait 4:5)":
        "https://framerusercontent.com/images/zCpuWkiGwOvPZwzZ3RoDdjACPhA.jpg",
      "Image 2 (Portrait 4:5):alt": "",
      "Image 3 (Landscape 4:3)":
        "https://framerusercontent.com/images/iOZqJPKA9gnWlCq3EVuVMslguQ.jpg",
      "Image 3 (Landscape 4:3):alt": "",
      "Image 4 (Portrait 4:5)": "",
      "Image 4 (Portrait 4:5):alt": "",
      "Image 5 (Portrait 4:5)": "",
      "Image 5 (Portrait 4:5):alt": "",
      "Image 6 (Landscape 4:3)": "",
      "Image 6 (Landscape 4:3):alt": "",
      "Image 7 (Portrait 4:5)": "",
      "Image 7 (Portrait 4:5):alt": "",
      "Image 8 (Portrait 4:5)": "",
      "Image 8 (Portrait 4:5):alt": "",
      "Image 9 (Landscape 4:3)": "",
      "Image 9 (Landscape 4:3):alt": "",
      "Image 10 (Portrait 4:5)": "",
      "Image 10 (Portrait 4:5):alt": "",
      "Image 11 (Portrait 4:5)": "",
      "Image 11 (Portrait 4:5):alt": "",
      "Image 12 (Landscape 4:3)": "",
      "Image 12 (Landscape 4:3):alt": "",
      "Featured Video (Landscape 16:9)": "",
      "Featured Video Poster": "",
      "Featured Video Poster:alt": "",
      "Video 1 (Portrait 4:5)": "",
      "Video 2 (Portrait 4:5)": "",
      "Video 3 (Landscape 16:9)": "",
      "Video 4 (Portrait 4:5)": "",
      "Video 5 (Portrait 4:5)": "",
      "Video 6 (Landscape 16:9)": "",
      "Video 7 (Portrait 4:5)": "",
      "Video 8 (Portrait 4:5)": "",
      "Video 9 (Landscape 16:9)": "",
      "Video 10 (Portrait 4:5)": "",
      "Video 11 (Portrait 4:5)": "",
      "Video 12 (Landscape 16:9)": "",
    },
    {
      Slug: "tierra-viva",
      Title: "Tierra Viva",
      "Homepage Featured": true,
      "Project Number": 5,
      "Next Project 1": 4,
      "Next Project 2": 3,
      "Next Project 3": 2,
      Tagline: "Breathing new life into an organic market",
      Client: "",
      Year: 2024,
      Location: "CDMX, Mexico",
      Info: "Tierra Viva, a well-known organic market in Coyoacán, approached me for a full brand refresh. I developed a new identity system inspired by natural textures and fresh produce, creating a vibrant logo, earthy color palette, and sustainable packaging for their products.",
      "External Link": "https://framer.link/ludoviclosco",
      Services: "visual-identity,brand-strategy",
      Credits: "<p>Images generated with AI</p>",
      "Thumbnail Image (Portrait 4:5)":
        "https://framerusercontent.com/images/pr9BvjBWOBB0MeBvdryWgvng.png",
      "Thumbnail Image (Portrait 4:5):alt": "",
      "Thumbnail Video (Portrait 4:5)": "",
      "Thumbnail Video Poster (Portrait 4:5)": "",
      "Thumbnail Video Poster (Portrait 4:5):alt": "",
      "Featured Image (Landscape 16:9)":
        "https://framerusercontent.com/images/pr9BvjBWOBB0MeBvdryWgvng.png",
      "Featured Image (Landscape 16:9):alt": "",
      "Image 1 (Portrait 4:5)":
        "https://framerusercontent.com/images/lXAM68WPSxArMZbGt0dVP4qY4EU.png",
      "Image 1 (Portrait 4:5):alt": "",
      "Image 2 (Portrait 4:5)":
        "https://framerusercontent.com/images/m4GfjOpmlji7cBFCi2vvTcLewU.png",
      "Image 2 (Portrait 4:5):alt": "",
      "Image 3 (Landscape 4:3)":
        "https://framerusercontent.com/images/w29t0WqbllDKStfCAoeFnfLioXo.png",
      "Image 3 (Landscape 4:3):alt": "",
      "Image 4 (Portrait 4:5)": "",
      "Image 4 (Portrait 4:5):alt": "",
      "Image 5 (Portrait 4:5)": "",
      "Image 5 (Portrait 4:5):alt": "",
      "Image 6 (Landscape 4:3)": "",
      "Image 6 (Landscape 4:3):alt": "",
      "Image 7 (Portrait 4:5)": "",
      "Image 7 (Portrait 4:5):alt": "",
      "Image 8 (Portrait 4:5)": "",
      "Image 8 (Portrait 4:5):alt": "",
      "Image 9 (Landscape 4:3)": "",
      "Image 9 (Landscape 4:3):alt": "",
      "Image 10 (Portrait 4:5)": "",
      "Image 10 (Portrait 4:5):alt": "",
      "Image 11 (Portrait 4:5)": "",
      "Image 11 (Portrait 4:5):alt": "",
      "Image 12 (Landscape 4:3)": "",
      "Image 12 (Landscape 4:3):alt": "",
      "Featured Video (Landscape 16:9)": "",
      "Featured Video Poster": "",
      "Featured Video Poster:alt": "",
      "Video 1 (Portrait 4:5)": "",
      "Video 2 (Portrait 4:5)": "",
      "Video 3 (Landscape 16:9)": "",
      "Video 4 (Portrait 4:5)": "",
      "Video 5 (Portrait 4:5)": "",
      "Video 6 (Landscape 16:9)": "",
      "Video 7 (Portrait 4:5)": "",
      "Video 8 (Portrait 4:5)": "",
      "Video 9 (Landscape 16:9)": "",
      "Video 10 (Portrait 4:5)": "",
      "Video 11 (Portrait 4:5)": "",
      "Video 12 (Landscape 16:9)": "",
    },
    {
      Slug: "casa-nomad",
      Title: "Casa Nomad",
      "Homepage Featured": true,
      "Project Number": 4,
      "Next Project 1": 3,
      "Next Project 2": 2,
      "Next Project 3": 1,
      Tagline: "Weaving artisan stories into a global brand",
      Client: "",
      Year: 2025,
      Location: "Oaxaca & CDMX",
      Info: "Casa Nomad invited me to build a brand that honored the authenticity of Oaxacan artisans while appealing to a global audience. I crafted a rich, storytelling-driven identity, designed e-commerce experiences, and developed packaging that put the artisans’ work at center stage.",
      "External Link": "https://framer.link/ludoviclosco",
      Services: "art-direction,digital",
      Credits: "<p>Images generated with AI</p>",
      "Thumbnail Image (Portrait 4:5)":
        "https://framerusercontent.com/images/gSPlJuwM0MKIuMDtrd15gqVOOLQ.jpg",
      "Thumbnail Image (Portrait 4:5):alt": "",
      "Thumbnail Video (Portrait 4:5)": "",
      "Thumbnail Video Poster (Portrait 4:5)": "",
      "Thumbnail Video Poster (Portrait 4:5):alt": "",
      "Featured Image (Landscape 16:9)":
        "https://framerusercontent.com/images/gSPlJuwM0MKIuMDtrd15gqVOOLQ.jpg",
      "Featured Image (Landscape 16:9):alt": "",
      "Image 1 (Portrait 4:5)":
        "https://framerusercontent.com/images/0yAjKJJUK8kRtiGcsTlwXhSkKQ.png",
      "Image 1 (Portrait 4:5):alt": "",
      "Image 2 (Portrait 4:5)":
        "https://framerusercontent.com/images/ICT2riETnouSdB34JYirzDsFTg.png",
      "Image 2 (Portrait 4:5):alt": "",
      "Image 3 (Landscape 4:3)":
        "https://framerusercontent.com/images/1WhNi7ojGOVTMW31eV3SJf5zBU.png",
      "Image 3 (Landscape 4:3):alt": "",
      "Image 4 (Portrait 4:5)": "",
      "Image 4 (Portrait 4:5):alt": "",
      "Image 5 (Portrait 4:5)": "",
      "Image 5 (Portrait 4:5):alt": "",
      "Image 6 (Landscape 4:3)": "",
      "Image 6 (Landscape 4:3):alt": "",
      "Image 7 (Portrait 4:5)": "",
      "Image 7 (Portrait 4:5):alt": "",
      "Image 8 (Portrait 4:5)": "",
      "Image 8 (Portrait 4:5):alt": "",
      "Image 9 (Landscape 4:3)": "",
      "Image 9 (Landscape 4:3):alt": "",
      "Image 10 (Portrait 4:5)": "",
      "Image 10 (Portrait 4:5):alt": "",
      "Image 11 (Portrait 4:5)": "",
      "Image 11 (Portrait 4:5):alt": "",
      "Image 12 (Landscape 4:3)": "",
      "Image 12 (Landscape 4:3):alt": "",
      "Featured Video (Landscape 16:9)": "",
      "Featured Video Poster": "",
      "Featured Video Poster:alt": "",
      "Video 1 (Portrait 4:5)": "",
      "Video 2 (Portrait 4:5)": "",
      "Video 3 (Landscape 16:9)": "",
      "Video 4 (Portrait 4:5)": "",
      "Video 5 (Portrait 4:5)": "",
      "Video 6 (Landscape 16:9)": "",
      "Video 7 (Portrait 4:5)": "",
      "Video 8 (Portrait 4:5)": "",
      "Video 9 (Landscape 16:9)": "",
      "Video 10 (Portrait 4:5)": "",
      "Video 11 (Portrait 4:5)": "",
      "Video 12 (Landscape 16:9)": "",
    },
    {
      Slug: "alba",
      Title: "Alba",
      "Homepage Featured": true,
      "Project Number": 3,
      "Next Project 1": 2,
      "Next Project 2": 1,
      "Next Project 3": 6,
      Tagline: "Crafting a sanctuary of minimalism and nature",
      Client: "",
      Year: 2024,
      Location: "CDMX, Mexico",
      Info: "Alba, a boutique hotel inspired by minimalism and natural beauty, trusted me to craft a timeless visual identity. I designed a custom logo, signage system, branded touchpoints throughout the hotel, and a full brand guidelines book to ensure a cohesive guest experience.",
      "External Link": "https://framer.link/ludoviclosco",
      Services: "brand-strategy,visual-identity",
      Credits: "<p>Images generated with AI</p>",
      "Thumbnail Image (Portrait 4:5)":
        "https://framerusercontent.com/images/GF4ssrVerG25QzdvMCyQSh48yHk.jpg",
      "Thumbnail Image (Portrait 4:5):alt": "",
      "Thumbnail Video (Portrait 4:5)": "",
      "Thumbnail Video Poster (Portrait 4:5)": "",
      "Thumbnail Video Poster (Portrait 4:5):alt": "",
      "Featured Image (Landscape 16:9)":
        "https://framerusercontent.com/images/dh14rW9iROprhnSBDL8m0TWc8Q.jpg",
      "Featured Image (Landscape 16:9):alt": "",
      "Image 1 (Portrait 4:5)":
        "https://framerusercontent.com/images/GF4ssrVerG25QzdvMCyQSh48yHk.jpg",
      "Image 1 (Portrait 4:5):alt": "",
      "Image 2 (Portrait 4:5)":
        "https://framerusercontent.com/images/zn1gqfclTjIIkpl6h1ZzM0f9qI.jpg",
      "Image 2 (Portrait 4:5):alt": "",
      "Image 3 (Landscape 4:3)":
        "https://framerusercontent.com/images/bL1ku7G9rtlNgyRiEPbmaJJ0qi4.jpg",
      "Image 3 (Landscape 4:3):alt": "",
      "Image 4 (Portrait 4:5)":
        "https://framerusercontent.com/images/VddkS6ctctpPNqdOqU9pWpCHpI.jpg",
      "Image 4 (Portrait 4:5):alt": "",
      "Image 5 (Portrait 4:5)":
        "https://framerusercontent.com/images/7iZ50lv5yhT8IU0SBph3uTQg.jpg",
      "Image 5 (Portrait 4:5):alt": "",
      "Image 6 (Landscape 4:3)": "",
      "Image 6 (Landscape 4:3):alt": "",
      "Image 7 (Portrait 4:5)": "",
      "Image 7 (Portrait 4:5):alt": "",
      "Image 8 (Portrait 4:5)": "",
      "Image 8 (Portrait 4:5):alt": "",
      "Image 9 (Landscape 4:3)": "",
      "Image 9 (Landscape 4:3):alt": "",
      "Image 10 (Portrait 4:5)": "",
      "Image 10 (Portrait 4:5):alt": "",
      "Image 11 (Portrait 4:5)": "",
      "Image 11 (Portrait 4:5):alt": "",
      "Image 12 (Landscape 4:3)": "",
      "Image 12 (Landscape 4:3):alt": "",
      "Featured Video (Landscape 16:9)":
        "https://framerusercontent.com/assets/367Uv7c1cVpUQ7Zfd3BgSsHbaws.mp4",
      "Featured Video Poster": "",
      "Featured Video Poster:alt": "",
      "Video 1 (Portrait 4:5)": "",
      "Video 2 (Portrait 4:5)": "",
      "Video 3 (Landscape 16:9)": "",
      "Video 4 (Portrait 4:5)": "",
      "Video 5 (Portrait 4:5)": "",
      "Video 6 (Landscape 16:9)": "",
      "Video 7 (Portrait 4:5)": "",
      "Video 8 (Portrait 4:5)": "",
      "Video 9 (Landscape 16:9)": "",
      "Video 10 (Portrait 4:5)": "",
      "Video 11 (Portrait 4:5)": "",
      "Video 12 (Landscape 16:9)": "",
    },
    {
      Slug: "luz-de-tierra",
      Title: "Luz de Tierra",
      "Homepage Featured": false,
      "Project Number": 2,
      "Next Project 1": 1,
      "Next Project 2": 6,
      "Next Project 3": 5,
      Tagline: "Designing a skincare brand rooted in nature",
      Client: "",
      Year: 2024,
      Location: "Oaxaca, Mexico",
      Info: "Luz de Tierra is a new skincare brand born in Oaxaca, focused on natural ingredients and sustainable practices. I was brought in to create a calm, confident identity that would reflect their values, slow beauty, earth-based formulas, and ethical sourcing.",
      "External Link": "https://framer.link/ludoviclosco",
      Services: "packaging,brand-strategy",
      Credits: "<p>Images generated with AI</p>",
      "Thumbnail Image (Portrait 4:5)":
        "https://framerusercontent.com/images/QhjTe3NiQv8FLstlX93kYBwNXT8.png",
      "Thumbnail Image (Portrait 4:5):alt": "",
      "Thumbnail Video (Portrait 4:5)": "",
      "Thumbnail Video Poster (Portrait 4:5)": "",
      "Thumbnail Video Poster (Portrait 4:5):alt": "",
      "Featured Image (Landscape 16:9)":
        "https://framerusercontent.com/images/TrXKx0gH3whrVIEqpD9jlKrvUA.png",
      "Featured Image (Landscape 16:9):alt": "",
      "Image 1 (Portrait 4:5)":
        "https://framerusercontent.com/images/1L456BaOSMRWTz1Mrf1cexaOvTc.png",
      "Image 1 (Portrait 4:5):alt": "",
      "Image 2 (Portrait 4:5)":
        "https://framerusercontent.com/images/QhjTe3NiQv8FLstlX93kYBwNXT8.png",
      "Image 2 (Portrait 4:5):alt": "",
      "Image 3 (Landscape 4:3)":
        "https://framerusercontent.com/images/YkKYSQGpjXWgNdC7uNz3XDYfHRY.png",
      "Image 3 (Landscape 4:3):alt": "",
      "Image 4 (Portrait 4:5)": "",
      "Image 4 (Portrait 4:5):alt": "",
      "Image 5 (Portrait 4:5)": "",
      "Image 5 (Portrait 4:5):alt": "",
      "Image 6 (Landscape 4:3)": "",
      "Image 6 (Landscape 4:3):alt": "",
      "Image 7 (Portrait 4:5)": "",
      "Image 7 (Portrait 4:5):alt": "",
      "Image 8 (Portrait 4:5)": "",
      "Image 8 (Portrait 4:5):alt": "",
      "Image 9 (Landscape 4:3)": "",
      "Image 9 (Landscape 4:3):alt": "",
      "Image 10 (Portrait 4:5)": "",
      "Image 10 (Portrait 4:5):alt": "",
      "Image 11 (Portrait 4:5)": "",
      "Image 11 (Portrait 4:5):alt": "",
      "Image 12 (Landscape 4:3)": "",
      "Image 12 (Landscape 4:3):alt": "",
      "Featured Video (Landscape 16:9)": "",
      "Featured Video Poster": "",
      "Featured Video Poster:alt": "",
      "Video 1 (Portrait 4:5)": "",
      "Video 2 (Portrait 4:5)": "",
      "Video 3 (Landscape 16:9)": "",
      "Video 4 (Portrait 4:5)": "",
      "Video 5 (Portrait 4:5)": "",
      "Video 6 (Landscape 16:9)": "",
      "Video 7 (Portrait 4:5)": "",
      "Video 8 (Portrait 4:5)": "",
      "Video 9 (Landscape 16:9)": "",
      "Video 10 (Portrait 4:5)": "",
      "Video 11 (Portrait 4:5)": "",
      "Video 12 (Landscape 16:9)": "",
    },
    {
      Slug: "la-mesa",
      Title: "La Mesa",
      "Homepage Featured": false,
      "Project Number": 1,
      "Next Project 1": 6,
      "Next Project 2": 5,
      "Next Project 3": 4,
      Tagline: "Blending tradition and modernity through design",
      Client: "",
      Year: 2025,
      Location: "Roma Norte, CDMX",
      Info: "La Mesa approached me to design a modern twist on traditional Mexican culinary branding. I developed a playful yet elegant identity system, combining bold colors, handmade typography, and mural designs that celebrate the spirit of CDMX.",
      "External Link": "https://framer.link/ludoviclosco",
      Services: "marketing-materials,packaging",
      Credits: "<p>Images by Unsplash</p>",
      "Thumbnail Image (Portrait 4:5)":
        "https://framerusercontent.com/images/L9p5AcNOO4D4JyhyF3tQeZqMVo.jpg",
      "Thumbnail Image (Portrait 4:5):alt": "",
      "Thumbnail Video (Portrait 4:5)": "",
      "Thumbnail Video Poster (Portrait 4:5)": "",
      "Thumbnail Video Poster (Portrait 4:5):alt": "",
      "Featured Image (Landscape 16:9)":
        "https://framerusercontent.com/images/L9p5AcNOO4D4JyhyF3tQeZqMVo.jpg",
      "Featured Image (Landscape 16:9):alt": "",
      "Image 1 (Portrait 4:5)":
        "https://framerusercontent.com/images/vZ8fxm86XxQJuqvKv9wWZrMjKyE.jpg",
      "Image 1 (Portrait 4:5):alt": "",
      "Image 2 (Portrait 4:5)":
        "https://framerusercontent.com/images/PDs182Dg8bmoFmHcmuycbV5GNY.jpg",
      "Image 2 (Portrait 4:5):alt": "",
      "Image 3 (Landscape 4:3)":
        "https://framerusercontent.com/images/0V6zxD08oIkpMaU5PodvSBCeME.jpg",
      "Image 3 (Landscape 4:3):alt": "",
      "Image 4 (Portrait 4:5)": "",
      "Image 4 (Portrait 4:5):alt": "",
      "Image 5 (Portrait 4:5)": "",
      "Image 5 (Portrait 4:5):alt": "",
      "Image 6 (Landscape 4:3)": "",
      "Image 6 (Landscape 4:3):alt": "",
      "Image 7 (Portrait 4:5)": "",
      "Image 7 (Portrait 4:5):alt": "",
      "Image 8 (Portrait 4:5)": "",
      "Image 8 (Portrait 4:5):alt": "",
      "Image 9 (Landscape 4:3)": "",
      "Image 9 (Landscape 4:3):alt": "",
      "Image 10 (Portrait 4:5)": "",
      "Image 10 (Portrait 4:5):alt": "",
      "Image 11 (Portrait 4:5)": "",
      "Image 11 (Portrait 4:5):alt": "",
      "Image 12 (Landscape 4:3)": "",
      "Image 12 (Landscape 4:3):alt": "",
      "Featured Video (Landscape 16:9)": "",
      "Featured Video Poster": "",
      "Featured Video Poster:alt": "",
      "Video 1 (Portrait 4:5)": "",
      "Video 2 (Portrait 4:5)": "",
      "Video 3 (Landscape 16:9)": "",
      "Video 4 (Portrait 4:5)": "",
      "Video 5 (Portrait 4:5)": "",
      "Video 6 (Landscape 16:9)": "",
      "Video 7 (Portrait 4:5)": "",
      "Video 8 (Portrait 4:5)": "",
      "Video 9 (Landscape 16:9)": "",
      "Video 10 (Portrait 4:5)": "",
      "Video 11 (Portrait 4:5)": "",
      "Video 12 (Landscape 16:9)": "",
    },
  ],
  profileData: {
    name: "John Doe",
    role: "Photographer & Developer",
    info: "Let’s create something meaningful together. I’d love to hear about your project, big or small.",
    contact: {
      email: "recaap@gmail.com",
      phone: "+8210 6577 7996",
    },
    social: [socialConfig.instagram, socialConfig.github],
    image:
      "https://framerusercontent.com/images/HFh5kLnilRLgrC1PZNvmx0PRRA.jpg?scale-down-to=2048&width=3746&height=5226",
  },
};
